server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

logging:
  level:
    org.springframework.boot.context.config: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
