version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"
    networks:
      - spring-cloud

  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "8888:8888"
    networks:
      - spring-cloud
    environment:
      SPRING_PROFILES_ACTIVE: native
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - spring-cloud

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      config-service:
        condition: service_healthy
      mysql:
        condition: service_started
      discovery-service:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - spring-cloud
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888
      SPRING_APPLICATION_NAME: auth-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka

networks:
  spring-cloud:
    driver: bridge
